# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-25 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20170625_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='summary',
            field=models.TextField(blank=True, help_text='An event summary which will be shown on index page'),
        ),
    ]
