# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-25 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20170625_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='datetime_from',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Start datetime'),
        ),
    ]
