# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-28 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20170625_2034'),
        ('wagtailcore', '0033_remove_golive_expiry_help_text'),
        ('events', '0008_auto_20170625_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomEventSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='submit time')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.User')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='customeventsubmission',
            unique_together=set([('page', 'user')]),
        ),
    ]
