# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-01 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20170628_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeventsubmission',
            options={'ordering': ['created_at'], 'verbose_name': 'form submission'},
        ),
        migrations.AlterUniqueTogether(
            name='customeventsubmission',
            unique_together=set([]),
        ),
    ]
