# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-01 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0033_remove_golive_expiry_help_text'),
        ('authentication', '0009_auto_20170629_1638'),
        ('events', '0010_auto_20170701_0814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeventsubmission',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='customeventsubmission',
            unique_together=set([('page', 'user')]),
        ),
    ]
