# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-28 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20170701_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistrationpage',
            name='registration_form_status',
            field=models.SmallIntegerField(choices=[(0, 'Open for All'), (1, 'Open for users who already registered'), (2, 'Closed')], default=0),
        ),
    ]
