# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-09 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0016_deprecate_rendition_filter_relation'),
        ('locations', '0001_initial'),
        ('skills', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personskillsrelationship',
            name='skills',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills_person_relationship', to='skills.SkillsPage'),
        ),
        migrations.AddField(
            model_name='personpage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Person image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='personlocationrelationship',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_person_relationship', to='locations.LocationPage'),
        ),
        migrations.AddField(
            model_name='personlocationrelationship',
            name='person_page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_location_relationship', to='people.PersonPage'),
        ),
        migrations.AddField(
            model_name='personindexpage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='People listing image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
