# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-26 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20170609_2130'),
        ('people', '0002_auto_20170626_2053'),
    ]

    operations = [
    ]
