# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-25 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='m',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='not filled', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='institution',
            field=models.CharField(default='not filled', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='not filled', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
