# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-25 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20170625_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='division',
            field=models.CharField(default='Two', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='tshirt_size',
            field=models.CharField(default='L', max_length=4),
        ),
    ]
