# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-24 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_auto_20170928_0658'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('secret', models.CharField(db_index=True, max_length=255, unique=True)),
                ('valid', models.BooleanField(default=True)),
                ('description', models.CharField(db_index=True, default='', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
