# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-24 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_apiauth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiauth',
            name='secret',
            field=models.CharField(db_index=True, editable=False, max_length=255, unique=True),
        ),
    ]
